//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/SimplestarGame/SimpleXR/Input/XRControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/SimplestarGame/SimpleXR/Input/XRControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @XRControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @XRControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""XRControls"",
    ""maps"": [
        {
            ""name"": ""XRControlsActions"",
            ""id"": ""46a446bf-e252-490d-8feb-9285fa70477f"",
            ""actions"": [
                {
                    ""name"": ""LeftControllerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""93f7155a-e942-4720-b2ed-b1d733a19a1a"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""408a7ba1-609f-4095-95d8-2582df7e4b70"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""4b25e602-f46c-45d6-a9e2-b285ee395f47"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""18737569-10da-4e07-b525-751f5ca4b2c5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerRotation"",
                    ""type"": ""Value"",
                    ""id"": ""559d1cfd-615f-48ee-8637-9f782dbbc6b6"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightControllerRotation"",
                    ""type"": ""Value"",
                    ""id"": ""8c36f394-2631-465d-a568-717db3da255a"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftControllerGrip"",
                    ""type"": ""Button"",
                    ""id"": ""ab5e2ae2-986d-441a-a951-e5251a71d1e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightControllerGrip"",
                    ""type"": ""Button"",
                    ""id"": ""96384da6-6a54-4a9f-92b2-96cebafa18f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c7d26140-a028-4e64-abc2-987855a1f3bd"",
                    ""path"": ""<XRController>{LeftHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3ddfb51-a566-4bcc-a840-b94548f15fc4"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bada0ac0-c172-4e80-ae53-bedfee6e6c6e"",
                    ""path"": ""<ViveController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bed91eb-8801-4de7-a8dd-ee8daaf2ec3b"",
                    ""path"": ""<ViveController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3d7542a-8d75-45ed-8419-e9578187b690"",
                    ""path"": ""<XRController>{LeftHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab85a95b-6d71-4b3b-944e-ffa4f54732c8"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fbd6b01-0654-4069-82f0-38781ca93fbc"",
                    ""path"": ""<ViveController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8bb36c1-516d-40f2-813c-ccbd7eb64758"",
                    ""path"": ""<ViveController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // XRControlsActions
        m_XRControlsActions = asset.FindActionMap("XRControlsActions", throwIfNotFound: true);
        m_XRControlsActions_LeftControllerPosition = m_XRControlsActions.FindAction("LeftControllerPosition", throwIfNotFound: true);
        m_XRControlsActions_RightControllerPosition = m_XRControlsActions.FindAction("RightControllerPosition", throwIfNotFound: true);
        m_XRControlsActions_LeftControllerTrigger = m_XRControlsActions.FindAction("LeftControllerTrigger", throwIfNotFound: true);
        m_XRControlsActions_RightControllerTrigger = m_XRControlsActions.FindAction("RightControllerTrigger", throwIfNotFound: true);
        m_XRControlsActions_LeftControllerRotation = m_XRControlsActions.FindAction("LeftControllerRotation", throwIfNotFound: true);
        m_XRControlsActions_RightControllerRotation = m_XRControlsActions.FindAction("RightControllerRotation", throwIfNotFound: true);
        m_XRControlsActions_LeftControllerGrip = m_XRControlsActions.FindAction("LeftControllerGrip", throwIfNotFound: true);
        m_XRControlsActions_RightControllerGrip = m_XRControlsActions.FindAction("RightControllerGrip", throwIfNotFound: true);
    }

    ~@XRControls()
    {
        UnityEngine.Debug.Assert(!m_XRControlsActions.enabled, "This will cause a leak and performance issues, XRControls.XRControlsActions.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // XRControlsActions
    private readonly InputActionMap m_XRControlsActions;
    private List<IXRControlsActionsActions> m_XRControlsActionsActionsCallbackInterfaces = new List<IXRControlsActionsActions>();
    private readonly InputAction m_XRControlsActions_LeftControllerPosition;
    private readonly InputAction m_XRControlsActions_RightControllerPosition;
    private readonly InputAction m_XRControlsActions_LeftControllerTrigger;
    private readonly InputAction m_XRControlsActions_RightControllerTrigger;
    private readonly InputAction m_XRControlsActions_LeftControllerRotation;
    private readonly InputAction m_XRControlsActions_RightControllerRotation;
    private readonly InputAction m_XRControlsActions_LeftControllerGrip;
    private readonly InputAction m_XRControlsActions_RightControllerGrip;
    /// <summary>
    /// Provides access to input actions defined in input action map "XRControlsActions".
    /// </summary>
    public struct XRControlsActionsActions
    {
        private @XRControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public XRControlsActionsActions(@XRControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "XRControlsActions/LeftControllerPosition".
        /// </summary>
        public InputAction @LeftControllerPosition => m_Wrapper.m_XRControlsActions_LeftControllerPosition;
        /// <summary>
        /// Provides access to the underlying input action "XRControlsActions/RightControllerPosition".
        /// </summary>
        public InputAction @RightControllerPosition => m_Wrapper.m_XRControlsActions_RightControllerPosition;
        /// <summary>
        /// Provides access to the underlying input action "XRControlsActions/LeftControllerTrigger".
        /// </summary>
        public InputAction @LeftControllerTrigger => m_Wrapper.m_XRControlsActions_LeftControllerTrigger;
        /// <summary>
        /// Provides access to the underlying input action "XRControlsActions/RightControllerTrigger".
        /// </summary>
        public InputAction @RightControllerTrigger => m_Wrapper.m_XRControlsActions_RightControllerTrigger;
        /// <summary>
        /// Provides access to the underlying input action "XRControlsActions/LeftControllerRotation".
        /// </summary>
        public InputAction @LeftControllerRotation => m_Wrapper.m_XRControlsActions_LeftControllerRotation;
        /// <summary>
        /// Provides access to the underlying input action "XRControlsActions/RightControllerRotation".
        /// </summary>
        public InputAction @RightControllerRotation => m_Wrapper.m_XRControlsActions_RightControllerRotation;
        /// <summary>
        /// Provides access to the underlying input action "XRControlsActions/LeftControllerGrip".
        /// </summary>
        public InputAction @LeftControllerGrip => m_Wrapper.m_XRControlsActions_LeftControllerGrip;
        /// <summary>
        /// Provides access to the underlying input action "XRControlsActions/RightControllerGrip".
        /// </summary>
        public InputAction @RightControllerGrip => m_Wrapper.m_XRControlsActions_RightControllerGrip;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_XRControlsActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="XRControlsActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(XRControlsActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="XRControlsActionsActions" />
        public void AddCallbacks(IXRControlsActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_XRControlsActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_XRControlsActionsActionsCallbackInterfaces.Add(instance);
            @LeftControllerPosition.started += instance.OnLeftControllerPosition;
            @LeftControllerPosition.performed += instance.OnLeftControllerPosition;
            @LeftControllerPosition.canceled += instance.OnLeftControllerPosition;
            @RightControllerPosition.started += instance.OnRightControllerPosition;
            @RightControllerPosition.performed += instance.OnRightControllerPosition;
            @RightControllerPosition.canceled += instance.OnRightControllerPosition;
            @LeftControllerTrigger.started += instance.OnLeftControllerTrigger;
            @LeftControllerTrigger.performed += instance.OnLeftControllerTrigger;
            @LeftControllerTrigger.canceled += instance.OnLeftControllerTrigger;
            @RightControllerTrigger.started += instance.OnRightControllerTrigger;
            @RightControllerTrigger.performed += instance.OnRightControllerTrigger;
            @RightControllerTrigger.canceled += instance.OnRightControllerTrigger;
            @LeftControllerRotation.started += instance.OnLeftControllerRotation;
            @LeftControllerRotation.performed += instance.OnLeftControllerRotation;
            @LeftControllerRotation.canceled += instance.OnLeftControllerRotation;
            @RightControllerRotation.started += instance.OnRightControllerRotation;
            @RightControllerRotation.performed += instance.OnRightControllerRotation;
            @RightControllerRotation.canceled += instance.OnRightControllerRotation;
            @LeftControllerGrip.started += instance.OnLeftControllerGrip;
            @LeftControllerGrip.performed += instance.OnLeftControllerGrip;
            @LeftControllerGrip.canceled += instance.OnLeftControllerGrip;
            @RightControllerGrip.started += instance.OnRightControllerGrip;
            @RightControllerGrip.performed += instance.OnRightControllerGrip;
            @RightControllerGrip.canceled += instance.OnRightControllerGrip;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="XRControlsActionsActions" />
        private void UnregisterCallbacks(IXRControlsActionsActions instance)
        {
            @LeftControllerPosition.started -= instance.OnLeftControllerPosition;
            @LeftControllerPosition.performed -= instance.OnLeftControllerPosition;
            @LeftControllerPosition.canceled -= instance.OnLeftControllerPosition;
            @RightControllerPosition.started -= instance.OnRightControllerPosition;
            @RightControllerPosition.performed -= instance.OnRightControllerPosition;
            @RightControllerPosition.canceled -= instance.OnRightControllerPosition;
            @LeftControllerTrigger.started -= instance.OnLeftControllerTrigger;
            @LeftControllerTrigger.performed -= instance.OnLeftControllerTrigger;
            @LeftControllerTrigger.canceled -= instance.OnLeftControllerTrigger;
            @RightControllerTrigger.started -= instance.OnRightControllerTrigger;
            @RightControllerTrigger.performed -= instance.OnRightControllerTrigger;
            @RightControllerTrigger.canceled -= instance.OnRightControllerTrigger;
            @LeftControllerRotation.started -= instance.OnLeftControllerRotation;
            @LeftControllerRotation.performed -= instance.OnLeftControllerRotation;
            @LeftControllerRotation.canceled -= instance.OnLeftControllerRotation;
            @RightControllerRotation.started -= instance.OnRightControllerRotation;
            @RightControllerRotation.performed -= instance.OnRightControllerRotation;
            @RightControllerRotation.canceled -= instance.OnRightControllerRotation;
            @LeftControllerGrip.started -= instance.OnLeftControllerGrip;
            @LeftControllerGrip.performed -= instance.OnLeftControllerGrip;
            @LeftControllerGrip.canceled -= instance.OnLeftControllerGrip;
            @RightControllerGrip.started -= instance.OnRightControllerGrip;
            @RightControllerGrip.performed -= instance.OnRightControllerGrip;
            @RightControllerGrip.canceled -= instance.OnRightControllerGrip;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="XRControlsActionsActions.UnregisterCallbacks(IXRControlsActionsActions)" />.
        /// </summary>
        /// <seealso cref="XRControlsActionsActions.UnregisterCallbacks(IXRControlsActionsActions)" />
        public void RemoveCallbacks(IXRControlsActionsActions instance)
        {
            if (m_Wrapper.m_XRControlsActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="XRControlsActionsActions.AddCallbacks(IXRControlsActionsActions)" />
        /// <seealso cref="XRControlsActionsActions.RemoveCallbacks(IXRControlsActionsActions)" />
        /// <seealso cref="XRControlsActionsActions.UnregisterCallbacks(IXRControlsActionsActions)" />
        public void SetCallbacks(IXRControlsActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_XRControlsActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_XRControlsActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="XRControlsActionsActions" /> instance referencing this action map.
    /// </summary>
    public XRControlsActionsActions @XRControlsActions => new XRControlsActionsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "XRControlsActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="XRControlsActionsActions.AddCallbacks(IXRControlsActionsActions)" />
    /// <seealso cref="XRControlsActionsActions.RemoveCallbacks(IXRControlsActionsActions)" />
    public interface IXRControlsActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "LeftControllerPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftControllerPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightControllerPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightControllerPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftControllerTrigger" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftControllerTrigger(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightControllerTrigger" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightControllerTrigger(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftControllerRotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftControllerRotation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightControllerRotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightControllerRotation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftControllerGrip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftControllerGrip(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightControllerGrip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightControllerGrip(InputAction.CallbackContext context);
    }
}
